### ISSUE TITLE
Unused ids

### ISSUE THREAD

**Issue by JulienBe** [sf17k/digitaljumper#1]
https://github.com/sf17k/digitaljumper/blob/a507d33c5681cb16171234a1e0cf15fa181482c4/client/src/com/drakelinglabs/digitaljumper/client/system/RenderSys.kt#L36

As far as I can tell, ids is never used. Does it serve an hidden purpose ?

**Comment by sf17k** [comment]
`ids` is used in `renderEntity(ids[i])` on line 38. This is a way of iterating over an IntBag. It looks awkward because, for performance reasons, an IntBag's `data` array has extra unused space at the end that we have to be careful to avoid.

https://github.com/sf17k/digitaljumper/blob/a507d33c5681cb16171234a1e0cf15fa181482c4/client/src/com/drakelinglabs/digitaljumper/client/system/RenderSys.kt#L35-L39
